### PR TITLE
Fixed environment yml file

### PR DESCRIPTION
**Pull request by ykhas**
Hi there,
I tried to run test.py in this repo fresh off of a clone, in a new conda environment, by executing 
`conda env create -f environment.yml`
However, I ran into a good number of errors which can be fixed by updating the environment.yml file as shown. Tested with a fresh anaconda environment and it seems to work fine.

If there is an interest, I could also generate an environment.lock.yml file for reproducible conda builds.

### CODE REVIEW

**Comment by astanziola** [comment]
Thanks for the PR @ykhas and for spotting the issue! I tried to run `python test.py` but I get [this issue again](https://github.com/ucl-bug/helmnet/pull/13)? Did you have to change anything else to make it run without problems?

Regarding the locked environment file, there's already a locked dependency list in the [`paper_version` branch](https://github.com/ucl-bug/helmnet/blob/paper_version/environment.yml), which is a frozen branch that allows to reproduce the results in the paper.

In principle I would agree to have a locked environment file in the main branch too, since some libraries are introducing breaking changes quite often. However, in my experience locked dependencies are hard to work with if you want to upgrade some libraries, which is what some people may want to do when forking the main branch.

I think that, perhaps, it makes sense to (finally) setup some CI and a dependabot that takes care of upgrading and testing dependencies?

**Comment by ykhas** [comment]
Thanks for taking a look @astanziola . 

Yup, I did have to make more changes - I've pushed them now as a new commit.
I also don't have a GPU currently to run this code on, so I added a couple of lines in this same pull request to permit the code to run on CPU. I can remove that and open a new pull request for that functionality, if you wish -- but since it was only a couple of lines, I left it in.

With regards to the environment lock file - sounds good. IMHO, for now, I think the environment.yml file should still be upgraded regardless, since I was unable to run `python test.py` previously. Dependabot sounds like a good long-term workaround.

**Comment by ykhas** [comment]
Pushed a new commit with changes to test.py which make the call to load_from_checkpoint() look the same as it does in [the issue you sent previously](https://github.com/ucl-bug/helmnet/pull/13)

**Comment by astanziola** [comment]
Hello @ykhas ! Sorry so much if it took ages to get back to you on this... I just tested it and looks all right to me, thank you very much again for the help with this issue!

**Pull request merged**
